#!/bin/bash
#SBATCH -J MIMIC5

#SBATCH --time=48:00:00
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=2400
#SBATCH --gres=gpu:quadro_rtx_6000:1

#SBATCH --mail-user=jun.1.wang@kcl.ac.uk


#SBATCH --mail-type=BEGIN

#SBATCH --mail-type=END

#SBATCH --mail-type=FAIL

#SBATCH --mail-type=REQUEUE

#SBATCH --mail-type=ALL



module purge

module load GCC/10.2.0
module load OpenMPI/4.0.5
module load Java/1.8.0_292-OpenJDK

source ~/.bash_profile
source activate tc110_cd113
srun sh cfg/run_mimic5.sh
